In [ ]:
#english_score = np.array([55,89,76,65,48,70])

#math_score = np.array([60,85,60,68,np.nan,60])

#chinese_score = np.array([65,90,82,72,66,77])



#上 3 列共六位同學的英文、數學、國文成績，第一個元素代表第一位同學，舉例第一位同學英文 55 分、數學 60 分、國文 65 分，今天第五位同學因某原因沒來考試，導致數學成績缺值，運用上列數據回答下列問題。



#請計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略？
#第五位同學補考數學後成績為 55，請計算補考後數學成績平均、最大值、最小值、標準差？
#用補考後資料找出與國文成績相關係數最高的學科？

In [1]:
#loading numpy
import numpy as np

In [42]:
english_score = np.array([55,89,76,65,48,70])

math_score = np.array([60,85,60,68,np.nan,60])

chinese_score = np.array([65,90,82,72,66,77])

In [43]:
# self-define function to output the mean, max,min and Sd 
# max:numpy.nanmax();min:numpy.nanmin();mean:numpy.mean();SD:nanstd()*(omit the nan automatic)

#get the name of array
def namestr(obj, namespace):
    return [name for name in namespace if namespace[name] is obj]


def DS(score):
    name=input("What is the subject?")
    a=np.nanmax(score)
    b=np.nanmin(score)
    c=np.nanmean(score)
    d=np.nanstd(score)
    print(name,":","\n","Max:",a,"\n","Min:",b,"\n","Mean:",'%.3f'%c,"\n","Standard deviation(SD):",'%.3f'%d)
    


In [45]:
#Q1計算各科成績平均、最大值、最小值、標準差，其中數學缺一筆資料可忽略？
DS(english_score)
DS(math_score)
DS(chinese_score)

What is the subject?English
English : 
 Max: 89 
 Min: 48 
 Mean: 67.167 
 Standard deviation(SD): 13.434
What is the subject?Math
Math : 
 Max: 85.0 
 Min: 60.0 
 Mean: 66.600 
 Standard deviation(SD): 9.708
What is the subject?Chinese
Chinese : 
 Max: 90 
 Min: 65 
 Mean: 75.333 
 Standard deviation(SD): 8.825


In [46]:
#Q2#第五位同學補考數學後成績為 55，請計算補考後數學成績平均、最大值、最小值、標準差？
# replace nan value
math_scorer=math_score
math_scorer[np.isnan(math_scorer)]=55
math_scorer
DS(math_scorer)

What is the subject?Math_r
Math_r : 
 Max: 85.0 
 Min: 55.0 
 Mean: 64.667 
 Standard deviation(SD): 9.860


In [52]:
#Q3.用補考後資料找出與國文成績相關係數最高的學科？

CE=np.corrcoef(chinese_score, english_score)
CM=np.corrcoef(chinese_score, math_scorer)
print(CE)
print(CM)
np.greater_equal(CE, CM)

# Chinese and English has higher correlation than Chinsese and Math

[[1.         0.97792828]
 [0.97792828 1.        ]]
[[1.         0.74056803]
 [0.74056803 1.        ]]


array([[ True,  True],
       [ True,  True]])