In [ ]:
#array1 = np.array([[10, 8], [3, 5]])

#運用上列array計算反矩陣，乘上原矩陣，並觀察是否為單位矩陣?
#運用上列array計算特徵值、特徵向量?
#運用上列array計算SVD?

In [7]:
# loading package
import numpy as np

array1 = np.array([[10, 8], [3, 5]])

#反矩陣
r_array1=np.linalg.inv(array1)
# 矩陣乘法
A1=array1@r_array1
A2=np.eye(2)
print(A1)
print(A2)


[[1. 0.]
 [0. 1.]]
[[1. 0.]
 [0. 1.]]


In [12]:
#特徵值、特徵向量 :numpy.eig()
w,v=np.linalg.eig(array1)
print("特徵值:", w)
print('特徵向量:', v)

特徵值: [13.  2.]
特徵向量: [[ 0.93632918 -0.70710678]
 [ 0.35112344  0.70710678]]


In [8]:
#運用上列array計算SVD

np.linalg.svd(array1)

(array([[-0.91663818, -0.39971796],
        [-0.39971796,  0.91663818]]),
 array([13.94721714,  1.86417116]),
 array([[-0.74319741, -0.6690722 ],
        [-0.6690722 ,  0.74319741]]))